import { getDb } from "./db";
import { properties, users } from "../drizzle/schema";

// Hungarian property data - 20 demo homes
const hungarianProperties = [
  {
    title: "Modern Apartment in Budapest City Center",
    description: "Stunning 2-bedroom apartment in the heart of Budapest, walking distance to the Danube and Parliament. Fully furnished with modern amenities, perfect for professionals or students.",
    address: "Andrássy út 42",
    city: "Budapest",
    country: "Hungary",
    latitude: "47.5025",
    longitude: "19.0625",
    bedrooms: 2,
    bathrooms: 1,
    squareFeet: 850,
    maxGuests: 4,
    pricePerMonth: 320000,
    currency: "HUF",
    amenities: ["WiFi", "Air Conditioning", "Washing Machine", "Dishwasher", "Balcony", "Parking"],
    images: ["https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=800", "https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=800"],
    rentalType: "both",
    minStayDays: 30,
    lifestyleCategory: "business",
    featured: true,
  },
  {
    title: "Cozy Studio in Debrecen University District",
    description: "Perfect for students! This cozy studio is located near the University of Debrecen campus with excellent public transport connections.",
    address: "Egyetem tér 7",
    city: "Debrecen",
    country: "Hungary",
    latitude: "47.5333",
    longitude: "21.6333",
    bedrooms: 1,
    bathrooms: 1,
    squareFeet: 400,
    maxGuests: 2,
    pricePerMonth: 140000,
    currency: "HUF",
    amenities: ["WiFi", "Heating", "Study Desk", "Kitchen"],
    images: ["https://images.unsplash.com/photo-1502672023488-70e25813eb80?w=800"],
    rentalType: "long-term",
    minStayDays: 90,
    lifestyleCategory: "student",
    featured: false,
  },
  {
    title: "Spacious 3BR Family Home in Szeged",
    description: "Beautiful family home with garden in quiet residential area of Szeged. Close to schools and shopping centers.",
    address: "Kálvária sugárút 28",
    city: "Szeged",
    country: "Hungary",
    latitude: "46.2530",
    longitude: "20.1414",
    bedrooms: 3,
    bathrooms: 2,
    squareFeet: 1200,
    maxGuests: 6,
    pricePerMonth: 250000,
    currency: "HUF",
    amenities: ["WiFi", "Garden", "Parking", "Air Conditioning", "Pet Friendly", "Heating"],
    images: ["https://images.unsplash.com/photo-1568605114967-8130f3a36994?w=800", "https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=800"],
    rentalType: "long-term",
    minStayDays: 180,
    lifestyleCategory: "live",
    featured: true,
  },
  {
    title: "Luxury Penthouse in Budapest Castle District",
    description: "Exclusive penthouse with panoramic views of the Danube and Buda Castle. High-end finishes, rooftop terrace, and premium location.",
    address: "Várfok utca 15",
    city: "Budapest",
    country: "Hungary",
    latitude: "47.4987",
    longitude: "19.0348",
    bedrooms: 3,
    bathrooms: 2,
    squareFeet: 1500,
    maxGuests: 6,
    pricePerMonth: 780000,
    currency: "HUF",
    amenities: ["WiFi", "Air Conditioning", "Rooftop Terrace", "Gym", "Concierge", "Parking", "Smart Home"],
    images: ["https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?w=800", "https://images.unsplash.com/photo-1600607687644-aac4c3eac7f4?w=800"],
    rentalType: "both",
    minStayDays: 30,
    lifestyleCategory: "business",
    featured: true,
  },
  {
    title: "Affordable 1BR Near Miskolc Downtown",
    description: "Budget-friendly one-bedroom apartment close to Miskolc city center and public transport. Ideal for young professionals.",
    address: "Széchenyi utca 52",
    city: "Miskolc",
    country: "Hungary",
    latitude: "48.1035",
    longitude: "20.7784",
    bedrooms: 1,
    bathrooms: 1,
    squareFeet: 550,
    maxGuests: 2,
    pricePerMonth: 120000,
    currency: "HUF",
    amenities: ["WiFi", "Heating", "Kitchen", "Laundry"],
    images: ["https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=800"],
    rentalType: "both",
    minStayDays: 30,
    lifestyleCategory: "general",
    featured: false,
  },
  {
    title: "Modern Loft in Pécs Historic Center",
    description: "Stylish industrial loft in the heart of Pécs, near the university and cultural sites. High ceilings and modern design.",
    address: "Király utca 18",
    city: "Pécs",
    country: "Hungary",
    latitude: "46.0727",
    longitude: "18.2328",
    bedrooms: 2,
    bathrooms: 1,
    squareFeet: 900,
    maxGuests: 4,
    pricePerMonth: 220000,
    currency: "HUF",
    amenities: ["WiFi", "Air Conditioning", "High Ceilings", "Exposed Brick", "Modern Kitchen"],
    images: ["https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=800"],
    rentalType: "mid-term",
    minStayDays: 60,
    lifestyleCategory: "student",
    featured: false,
  },
  {
    title: "Riverside Apartment in Győr",
    description: "Beautiful apartment overlooking the Rába river in Győr. Walking distance to historic downtown and shopping areas.",
    address: "Rába rakpart 12",
    city: "Győr",
    country: "Hungary",
    latitude: "47.6875",
    longitude: "17.6504",
    bedrooms: 2,
    bathrooms: 1,
    squareFeet: 800,
    maxGuests: 4,
    pricePerMonth: 260000,
    currency: "HUF",
    amenities: ["WiFi", "River View", "Balcony", "Parking", "Heating", "Air Conditioning"],
    images: ["https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?w=800"],
    rentalType: "both",
    minStayDays: 30,
    lifestyleCategory: "live",
    featured: true,
  },
  {
    title: "Furnished Studio in Veszprém",
    description: "Compact and efficient studio apartment in Veszprém, perfect for solo travelers or students. Fully equipped kitchen.",
    address: "Óváros tér 5",
    city: "Veszprém",
    country: "Hungary",
    latitude: "47.0927",
    longitude: "17.9093",
    bedrooms: 1,
    bathrooms: 1,
    squareFeet: 380,
    maxGuests: 1,
    pricePerMonth: 110000,
    currency: "HUF",
    amenities: ["WiFi", "Kitchen", "Heating", "Study Desk"],
    images: ["https://images.unsplash.com/photo-1560185893-a55cbc8c57e8?w=800"],
    rentalType: "long-term",
    minStayDays: 90,
    lifestyleCategory: "student",
    featured: false,
  },
  {
    title: "Executive 2BR in Budapest Business District",
    description: "Premium apartment in Budapest's business district with office space, ideal for executives and remote workers.",
    address: "Váci út 76",
    city: "Budapest",
    country: "Hungary",
    latitude: "47.5200",
    longitude: "19.0700",
    bedrooms: 2,
    bathrooms: 2,
    squareFeet: 1000,
    maxGuests: 4,
    pricePerMonth: 450000,
    currency: "HUF",
    amenities: ["WiFi", "Office Space", "Air Conditioning", "Gym Access", "Parking", "Concierge"],
    images: ["https://images.unsplash.com/photo-1600607687920-4e2a09cf159d?w=800"],
    rentalType: "mid-term",
    minStayDays: 30,
    lifestyleCategory: "business",
    featured: true,
  },
  {
    title: "Charming 1BR in Eger Wine Region",
    description: "Delightful apartment in the historic town of Eger, famous for its wine cellars and castle. Perfect for wine enthusiasts.",
    address: "Dobó István tér 9",
    city: "Eger",
    country: "Hungary",
    latitude: "47.9024",
    longitude: "20.3770",
    bedrooms: 1,
    bathrooms: 1,
    squareFeet: 600,
    maxGuests: 2,
    pricePerMonth: 160000,
    currency: "HUF",
    amenities: ["WiFi", "Historic Building", "Heating", "Kitchen", "City View"],
    images: ["https://images.unsplash.com/photo-1600566753086-00f18fb6b3ea?w=800"],
    rentalType: "both",
    minStayDays: 30,
    lifestyleCategory: "general",
    featured: false,
  },
  {
    title: "Lake Balaton Beach House",
    description: "Stunning house right by Lake Balaton, Hungary's largest lake. Perfect summer retreat with private beach access.",
    address: "Parti sétány 23",
    city: "Siófok",
    country: "Hungary",
    latitude: "46.9028",
    longitude: "18.0522",
    bedrooms: 4,
    bathrooms: 2,
    squareFeet: 1600,
    maxGuests: 8,
    pricePerMonth: 520000,
    currency: "HUF",
    amenities: ["WiFi", "Lake Access", "Garden", "BBQ", "Parking", "Air Conditioning", "Beach Chairs"],
    images: ["https://images.unsplash.com/photo-1613490493576-7fde63acd811?w=800", "https://images.unsplash.com/photo-1600585154526-990dced4db0d?w=800"],
    rentalType: "mid-term",
    minStayDays: 30,
    lifestyleCategory: "live",
    featured: true,
  },
  {
    title: "Student Room in Szeged Shared Flat",
    description: "Affordable room in shared student flat near University of Szeged. Friendly international community.",
    address: "Tisza Lajos körút 45",
    city: "Szeged",
    country: "Hungary",
    latitude: "46.2465",
    longitude: "20.1480",
    bedrooms: 1,
    bathrooms: 1,
    squareFeet: 250,
    maxGuests: 1,
    pricePerMonth: 75000,
    currency: "HUF",
    amenities: ["WiFi", "Shared Kitchen", "Heating", "Study Desk", "Laundry"],
    images: ["https://images.unsplash.com/photo-1555854877-bab0e564b8d5?w=800"],
    rentalType: "long-term",
    minStayDays: 90,
    lifestyleCategory: "student",
    featured: false,
  },
  {
    title: "Renovated Flat in Budapest Jewish Quarter",
    description: "Newly renovated apartment in the vibrant Jewish Quarter, surrounded by ruin bars, cafes, and nightlife.",
    address: "Dob utca 35",
    city: "Budapest",
    country: "Hungary",
    latitude: "47.4958",
    longitude: "19.0619",
    bedrooms: 2,
    bathrooms: 1,
    squareFeet: 750,
    maxGuests: 4,
    pricePerMonth: 380000,
    currency: "HUF",
    amenities: ["WiFi", "Air Conditioning", "Modern Kitchen", "Balcony", "City Center"],
    images: ["https://images.unsplash.com/photo-1600585154363-67eb9e2e2099?w=800"],
    rentalType: "both",
    minStayDays: 30,
    lifestyleCategory: "live",
    featured: true,
  },
  {
    title: "Corporate Housing in Debrecen Tech Park",
    description: "Modern corporate apartment near Debrecen Technology Park. Ideal for business travelers and IT professionals.",
    address: "Böszörményi út 138",
    city: "Debrecen",
    country: "Hungary",
    latitude: "47.5486",
    longitude: "21.6350",
    bedrooms: 2,
    bathrooms: 1,
    squareFeet: 850,
    maxGuests: 3,
    pricePerMonth: 280000,
    currency: "HUF",
    amenities: ["WiFi", "Office Desk", "Parking", "Air Conditioning", "Gym", "Security"],
    images: ["https://images.unsplash.com/photo-1600566753151-384129cf4e3e?w=800"],
    rentalType: "mid-term",
    minStayDays: 30,
    lifestyleCategory: "business",
    featured: false,
  },
  {
    title: "Historic Apartment in Szentendre Art District",
    description: "Charming apartment in the artistic town of Szentendre, near galleries and the Danube Bend. Full of character.",
    address: "Dumtsa Jenő utca 12",
    city: "Szentendre",
    country: "Hungary",
    latitude: "47.6692",
    longitude: "19.0753",
    bedrooms: 1,
    bathrooms: 1,
    squareFeet: 550,
    maxGuests: 2,
    pricePerMonth: 190000,
    currency: "HUF",
    amenities: ["WiFi", "Historic Details", "Heating", "Kitchen", "Art District"],
    images: ["https://images.unsplash.com/photo-1600566752355-35792bedcfea?w=800"],
    rentalType: "both",
    minStayDays: 60,
    lifestyleCategory: "general",
    featured: false,
  },
  {
    title: "Modern 2BR in Kecskemét City Center",
    description: "Contemporary apartment in Kecskemét downtown, close to Art Nouveau architecture and local markets.",
    address: "Kossuth tér 3",
    city: "Kecskemét",
    country: "Hungary",
    latitude: "46.9060",
    longitude: "19.6917",
    bedrooms: 2,
    bathrooms: 1,
    squareFeet: 800,
    maxGuests: 4,
    pricePerMonth: 210000,
    currency: "HUF",
    amenities: ["WiFi", "Air Conditioning", "Balcony", "Parking", "Heating"],
    images: ["https://images.unsplash.com/photo-1600573472591-ee6b68d14bdb?w=800"],
    rentalType: "both",
    minStayDays: 30,
    lifestyleCategory: "live",
    featured: false,
  },
  {
    title: "Budget Studio in Nyíregyháza",
    description: "Affordable studio for students and young professionals in Nyíregyháza. Basic amenities, clean and functional.",
    address: "Bethlen Gábor utca 24",
    city: "Nyíregyháza",
    country: "Hungary",
    latitude: "47.9559",
    longitude: "21.7172",
    bedrooms: 1,
    bathrooms: 1,
    squareFeet: 350,
    maxGuests: 1,
    pricePerMonth: 95000,
    currency: "HUF",
    amenities: ["WiFi", "Kitchen", "Heating", "Study Area"],
    images: ["https://images.unsplash.com/photo-1600566752229-250ed79827d5?w=800"],
    rentalType: "long-term",
    minStayDays: 90,
    lifestyleCategory: "student",
    featured: false,
  },
  {
    title: "Premium 3BR in Budapest Margaret Island Area",
    description: "Luxurious 3-bedroom apartment near Margaret Island, one of Budapest's most prestigious locations. River views.",
    address: "Szent István körút 25",
    city: "Budapest",
    country: "Hungary",
    latitude: "47.5145",
    longitude: "19.0505",
    bedrooms: 3,
    bathrooms: 2,
    squareFeet: 1300,
    maxGuests: 6,
    pricePerMonth: 620000,
    currency: "HUF",
    amenities: ["WiFi", "River View", "Air Conditioning", "Balcony", "Parking", "Gym", "Concierge"],
    images: ["https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?w=800"],
    rentalType: "both",
    minStayDays: 30,
    lifestyleCategory: "business",
    featured: true,
  },
  {
    title: "Quiet 2BR in Sopron Historic Town",
    description: "Peaceful apartment in the charming border town of Sopron. Close to Austria, perfect for cross-border workers.",
    address: "Fő tér 8",
    city: "Sopron",
    country: "Hungary",
    latitude: "47.6852",
    longitude: "16.5839",
    bedrooms: 2,
    bathrooms: 1,
    squareFeet: 750,
    maxGuests: 4,
    pricePerMonth: 240000,
    currency: "HUF",
    amenities: ["WiFi", "Heating", "Kitchen", "Historic Center", "Parking"],
    images: ["https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=800"],
    rentalType: "long-term",
    minStayDays: 90,
    lifestyleCategory: "live",
    featured: false,
  },
  {
    title: "Spacious Family Home in Székesfehérvár",
    description: "Large family home with backyard in Székesfehérvár, Hungary's former royal seat. Great schools nearby.",
    address: "Árpád utca 44",
    city: "Székesfehérvár",
    country: "Hungary",
    latitude: "47.1926",
    longitude: "18.4289",
    bedrooms: 4,
    bathrooms: 2,
    squareFeet: 1400,
    maxGuests: 7,
    pricePerMonth: 320000,
    currency: "HUF",
    amenities: ["WiFi", "Garden", "Parking", "Pet Friendly", "Heating", "Air Conditioning", "Storage"],
    images: ["https://images.unsplash.com/photo-1600585154526-990dced4db0d?w=800"],
    rentalType: "long-term",
    minStayDays: 180,
    lifestyleCategory: "live",
    featured: true,
  },
];

async function seedHungaryProperties() {
  console.log("🇭🇺 Starting Hungarian properties seed...");

  const db = await getDb();

  // Get or create a landlord user
  const [landlord] = await db.select().from(users).where(users.userType === "landlord").limit(1);

  if (!landlord) {
    console.error("❌ No landlord user found. Please create a landlord user first.");
    return;
  }

  console.log(`✅ Found landlord user: ${landlord.name || landlord.email} (ID: ${landlord.id})`);

  // Insert all Hungarian properties
  for (const property of hungarianProperties) {
    try {
      await db.insert(properties).values({
        ...property,
        landlordId: landlord.id,
        available: true,
        viewCount: Math.floor(Math.random() * 500) + 50, // Random views
        favoriteCount: Math.floor(Math.random() * 50),
        inquiryCount: Math.floor(Math.random() * 30),
        createdAt: new Date(),
        updatedAt: new Date(),
      });
      console.log(`✅ Added: ${property.title} in ${property.city}`);
    } catch (error) {
      console.error(`❌ Failed to add ${property.title}:`, error);
    }
  }

  console.log("\n🎉 Hungarian properties seed completed!");
  console.log(`📊 Total properties added: ${hungarianProperties.length}`);

  // Summary by city
  const cityCounts = hungarianProperties.reduce((acc, prop) => {
    acc[prop.city] = (acc[prop.city] || 0) + 1;
    return acc;
  }, {} as Record<string, number>);

  console.log("\n📍 Properties by city:");
  Object.entries(cityCounts).forEach(([city, count]) => {
    console.log(`   ${city}: ${count}`);
  });
}

// Run the seed if called directly
if (import.meta.url === `file://${process.argv[1]}`) {
  seedHungaryProperties()
    .then(() => process.exit(0))
    .catch((error) => {
      console.error("❌ Seed failed:", error);
      process.exit(1);
    });
}

export { seedHungaryProperties };
