// Demo events data - like RAZ template seed data

import type { Event } from './types'

export const demoEvents: Event[] = [
  {
    id: 1,
    title: 'Summer BBQ Party',
    date: '2025-01-15',
    time: '18:00',
    type: 'public',
    category: 'friends',
    iconId: 'bbq',
    attendees: 24,
    confirmedAttendees: 24,
    location: 'Central Park',
    description:
      'Annual summer BBQ with games, music, and great food. Bring your own drinks!',
    hasVoting: false,
    hasTasks: true,
    hasPayment: false,
    organizerId: 'me',
    organizerName: 'Andor',
    status: 'fixed',
    tasks: [
      { id: 1, title: 'Buy charcoal', completed: true, assignee: 'Homer' },
      { id: 2, title: 'Setup tables', completed: true, assignee: 'Charlie Brown' },
      { id: 3, title: 'Prepare playlist', completed: true, assignee: 'Me' },
    ],
    participants: [
      { id: '1', name: 'Homer Simpson', status: 'confirmed' },
      { id: '2', name: 'Charlie Brown', status: 'confirmed' },
      { id: '3', name: 'SpongeBob SquarePants', status: 'confirmed' },
    ],
    resources: [
      {
        id: '1',
        type: 'drive',
        name: 'Event Planning',
        url: 'https://drive.google.com/folder',
      },
      {
        id: '2',
        type: 'photos',
        name: 'BBQ Photos',
        url: 'https://photos.google.com/album',
      },
    ],
    sharedDrive: 'https://drive.google.com',
    photos: 'https://photos.google.com',
  },
  {
    id: 2,
    title: 'Birthday Celebration',
    date: '2025-01-28',
    time: '19:00',
    type: 'private',
    category: 'friends',
    iconId: 'birthday',
    attendees: 15,
    confirmedAttendees: 12,
    location: 'My Place',
    description: 'Turning 30! Come celebrate with cake, drinks, and good vibes.',
    hasVoting: true,
    hasTasks: true,
    hasPayment: false,
    organizerId: 'me',
    organizerName: 'Andor',
    status: 'in-progress',
    tasks: [
      { id: 1, title: 'Order cake', completed: true },
      { id: 2, title: 'Send invites', completed: true },
      { id: 3, title: 'Buy decorations', completed: false },
    ],
    participants: [
      { id: '1', name: 'Marge Simpson', status: 'confirmed' },
      { id: '2', name: 'Bart Simpson', status: 'confirmed' },
      { id: '3', name: 'Lisa Simpson', status: 'pending' },
    ],
  },
  {
    id: 3,
    title: 'Weekend Ski Trip',
    date: '2025-02-08',
    time: '07:00',
    type: 'private',
    category: 'sports',
    iconId: 'ski',
    attendees: 6,
    confirmedAttendees: 4,
    location: 'Alpine Resort',
    description: 'Two days of skiing and relaxation in the mountains.',
    hasVoting: true,
    hasTasks: true,
    hasPayment: true,
    paymentAmount: 180,
    currency: 'EUR',
    organizerId: 'me',
    organizerName: 'Andor',
    status: 'optimal',
    tasks: [
      { id: 1, title: 'Book accommodation', completed: true },
      { id: 2, title: 'Rent equipment', completed: false },
      { id: 3, title: 'Arrange transport', completed: false },
    ],
    participants: [
      { id: '1', name: 'Patrick Star', status: 'confirmed' },
      { id: '2', name: 'Sandy Cheeks', status: 'confirmed' },
      { id: '3', name: 'Squidward Tentacles', status: 'pending' },
    ],
  },
  {
    id: 4,
    title: 'Game Night',
    date: '2025-01-18',
    time: '20:00',
    type: 'private',
    category: 'friends',
    iconId: 'gaming',
    attendees: 8,
    confirmedAttendees: 8,
    location: 'My Apartment',
    description: 'Board games, video games, snacks, and fun!',
    hasVoting: false,
    hasTasks: false,
    hasPayment: false,
    organizerId: 'me',
    organizerName: 'Andor',
    status: 'fixed',
    participants: [
      { id: '1', name: 'Mickey Mouse', status: 'confirmed' },
      { id: '2', name: 'Donald Duck', status: 'confirmed' },
      { id: '3', name: 'Goofy', status: 'confirmed' },
      { id: '4', name: 'Minnie Mouse', status: 'confirmed' },
    ],
  },
  {
    id: 13,
    title: 'Normafa IV.',
    date: '2026-02-23',
    time: '09:00',
    type: 'public',
    category: 'sports',
    iconId: 'hiking',
    attendees: 12,
    confirmedAttendees: 6,
    location: 'Budapest, Normafa',
    description: 'Group hike to Normafa, then coffee at the cabin.',
    hasVoting: true,
    hasTasks: true,
    hasPayment: false,
    organizerId: 'scooby',
    organizerName: 'Scooby-Doo',
    status: 'in-progress',
    tasks: [
      { id: 1, title: 'Check weather', completed: false },
      { id: 2, title: 'Share meetup point', completed: true },
    ],
    participants: [
      { id: 'me', name: 'Me', status: 'pending' },
      { id: '1', name: 'Shaggy Rogers', status: 'pending' },
      { id: '2', name: 'Velma Dinkley', status: 'confirmed' },
    ],
  },
  {
    id: 14,
    title: 'Team Offsite Q1',
    date: '2026-02-18',
    time: '10:00',
    type: 'private',
    category: 'work',
    iconId: 'meeting',
    attendees: 14,
    confirmedAttendees: 10,
    location: 'Office Conference Room A',
    description: 'Quarterly planning and team building.',
    hasVoting: true,
    hasTasks: true,
    hasPayment: false,
    organizerId: 'me',
    organizerName: 'Andor',
    status: 'optimal',
    participants: [
      { id: '1', name: 'Bugs Bunny', status: 'confirmed' },
      { id: '2', name: 'Daffy Duck', status: 'pending' },
    ],
  },
  {
    id: 15,
    title: 'Pizza Night',
    date: '2026-02-16',
    time: '19:00',
    type: 'private',
    category: 'friends',
    iconId: 'dinner',
    attendees: 6,
    confirmedAttendees: 4,
    location: 'Downtown Pizzeria',
    description: 'Casual get-together with pizza and drinks.',
    hasVoting: true,
    hasTasks: false,
    hasPayment: true,
    paymentAmount: 15,
    currency: 'EUR',
    organizerId: 'lisa',
    organizerName: 'Lisa Simpson',
    status: 'in-progress',
    participants: [
      { id: 'me', name: 'Me', status: 'confirmed' },
      { id: '1', name: 'Bart Simpson', status: 'confirmed' },
    ],
  },
  {
    id: 5,
    title: 'Family Reunion',
    date: '2025-01-20',
    time: '14:00',
    type: 'private',
    category: 'family',
    iconId: 'family',
    attendees: 25,
    confirmedAttendees: 18,
    location: "Grandma's House",
    description: 'Annual family gathering with dinner and catching up.',
    hasVoting: true,
    hasTasks: true,
    hasPayment: false,
    organizerId: 'marge',
    organizerName: 'Marge Simpson',
    status: 'optimal',
    tasks: [
      { id: 1, title: 'Send invitations', completed: true },
      { id: 2, title: 'Plan menu', completed: false },
    ],
    participants: [
      { id: 'me', name: 'Me', status: 'confirmed' },
      { id: '2', name: 'Abe Simpson', status: 'pending' },
      { id: '3', name: 'Maggie Simpson', status: 'confirmed' },
    ],
  },
  {
    id: 6,
    title: 'Tech Conference 2025',
    date: '2025-01-25',
    time: '09:00',
    type: 'public',
    category: 'work',
    iconId: 'work',
    attendees: 320,
    confirmedAttendees: 180,
    location: 'Convention Center',
    description: 'Annual tech conference featuring talks from industry leaders.',
    hasVoting: true,
    hasTasks: true,
    hasPayment: true,
    paymentAmount: 299,
    currency: 'USD',
    organizerId: 'homer',
    organizerName: 'Homer Simpson',
    status: 'in-progress',
    tasks: [
      { id: 1, title: 'Book speakers', completed: true },
      { id: 2, title: 'Setup registration', completed: true },
      { id: 3, title: 'Print badges', completed: false },
    ],
    participants: [
      { id: 'me', name: 'Me', status: 'confirmed' },
      { id: '2', name: 'Mr. Burns', status: 'confirmed' },
      { id: '3', name: 'Lenny Leonard', status: 'pending' },
    ],
    sharedDrive: 'https://drive.google.com',
    documents: 'https://docs.google.com',
  },
  {
    id: 7,
    title: 'Wedding Celebration',
    date: '2025-02-14',
    time: '16:00',
    type: 'private',
    category: 'family',
    iconId: 'wedding',
    attendees: 150,
    confirmedAttendees: 150,
    location: 'Garden Venue',
    description: 'Join us for our special day!',
    hasVoting: false,
    hasTasks: false,
    hasPayment: false,
    organizerId: 'homer',
    organizerName: 'Homer & Marge',
    status: 'fixed',
    participants: [
      { id: 'me', name: 'Me', status: 'confirmed' },
      { id: '2', name: 'Marge Simpson', status: 'confirmed' },
    ],
    resources: [
      {
        id: '1',
        type: 'photos',
        name: 'Wedding Album',
        url: 'https://photos.google.com/album',
      },
    ],
    photos: 'https://photos.google.com',
  },
  {
    id: 8,
    title: 'Hiking Adventure',
    date: '2025-02-01',
    time: '08:00',
    type: 'public',
    category: 'sports',
    iconId: 'hiking',
    attendees: 12,
    confirmedAttendees: 8,
    location: 'Mountain Trail',
    description: 'Day hike to the summit with experienced guides.',
    hasVoting: false,
    hasTasks: true,
    hasPayment: true,
    paymentAmount: 25,
    currency: 'EUR',
    organizerId: 'charlie',
    organizerName: 'Charlie Brown',
    status: 'in-progress',
    tasks: [
      {
        id: 1,
        title: 'Check weather',
        completed: false,
        assignee: 'Charlie Brown',
      },
      { id: 2, title: 'Pack supplies', completed: false, assignee: 'Snoopy' },
    ],
    participants: [
      { id: 'me', name: 'Me', status: 'confirmed' },
      { id: '2', name: 'Snoopy', status: 'confirmed' },
      { id: '3', name: 'Lucy van Pelt', status: 'pending' },
    ],
  },
  {
    id: 9,
    title: 'Wine Tasting Evening',
    date: '2025-02-05',
    time: '19:00',
    type: 'private',
    category: 'friends',
    iconId: 'dinner',
    attendees: 10,
    confirmedAttendees: 7,
    location: 'Wine Bar Downtown',
    description: 'An evening of fine wines and good conversation.',
    hasVoting: true,
    hasTasks: false,
    hasPayment: true,
    paymentAmount: 45,
    currency: 'EUR',
    organizerId: 'diana',
    organizerName: 'Wonder Woman',
    status: 'optimal',
    participants: [
      { id: 'me', name: 'Me', status: 'confirmed' },
      { id: '2', name: 'Batman', status: 'confirmed' },
      { id: '3', name: 'Superman', status: 'pending' },
    ],
  },
  {
    id: 10,
    title: 'Charity Fundraiser',
    date: '2025-02-20',
    time: '19:00',
    type: 'public',
    category: 'work',
    iconId: 'party',
    attendees: 200,
    confirmedAttendees: 85,
    location: 'Grand Hotel',
    description: 'Annual charity gala to support local initiatives.',
    hasVoting: true,
    hasTasks: true,
    hasPayment: true,
    paymentAmount: 50,
    currency: 'EUR',
    organizerId: 'edna',
    organizerName: 'Edna Mode',
    status: 'in-progress',
    tasks: [
      { id: 1, title: 'Contact sponsors', completed: true, assignee: 'Edna' },
      {
        id: 2,
        title: 'Arrange catering',
        completed: false,
        assignee: 'Wonder Woman',
      },
    ],
    participants: [
      { id: 'me', name: 'Me', status: 'confirmed' },
      { id: '2', name: 'Elastigirl', status: 'confirmed' },
    ],
    sharedDrive: 'https://drive.google.com',
    documents: 'https://docs.google.com',
  },
  {
    id: 11,
    title: 'Book Club Meeting',
    date: '2025-01-22',
    time: '18:30',
    type: 'private',
    category: 'friends',
    iconId: 'coffee',
    attendees: 8,
    confirmedAttendees: 6,
    location: 'Coffee House',
    description: 'Discussing "The Great Gatsby" this month.',
    hasVoting: false,
    hasTasks: false,
    hasPayment: false,
    organizerId: 'grace',
    organizerName: 'Minnie Mouse',
    status: 'fixed',
    participants: [
      { id: 'me', name: 'Me', status: 'confirmed' },
      { id: '2', name: 'Daisy Duck', status: 'confirmed' },
      { id: '3', name: 'Pluto', status: 'confirmed' },
    ],
  },
  {
    id: 12,
    title: 'Beach Volleyball Tournament',
    date: '2025-02-15',
    time: '10:00',
    type: 'public',
    category: 'sports',
    iconId: 'beach',
    attendees: 32,
    confirmedAttendees: 24,
    location: 'Sunset Beach',
    description: 'Friendly tournament with teams of 4. Prizes for winners!',
    hasVoting: true,
    hasTasks: true,
    hasPayment: true,
    paymentAmount: 15,
    currency: 'EUR',
    organizerId: 'peter',
    organizerName: 'Peter Griffin',
    status: 'in-progress',
    tasks: [
      { id: 1, title: 'Reserve beach area', completed: true },
      { id: 2, title: 'Get nets and balls', completed: true },
      { id: 3, title: 'Organize teams', completed: false },
    ],
    participants: [
      { id: 'me', name: 'Me', status: 'pending' },
      { id: '2', name: 'Lois Griffin', status: 'confirmed' },
      { id: '3', name: 'Stewie Griffin', status: 'confirmed' },
    ],
  },
  {
    id: 16,
    title: 'Camping Weekend',
    date: '2026-03-15',
    time: '14:00',
    type: 'public',
    category: 'sports',
    iconId: 'camping',
    attendees: 8,
    confirmedAttendees: 5,
    location: 'Lake Balaton',
    description: 'Two nights under the stars. Bring your tent!',
    hasVoting: true,
    hasTasks: true,
    hasPayment: true,
    paymentAmount: 20,
    currency: 'EUR',
    organizerId: 'me',
    organizerName: 'Andor',
    status: 'optimal',
    participants: [
      { id: '1', name: 'Patrick Star', status: 'confirmed' },
      { id: '2', name: 'Shaggy Rogers', status: 'pending' },
    ],
  },
  {
    id: 17,
    title: 'Coffee & Code Morning',
    date: '2026-03-01',
    time: '09:00',
    type: 'private',
    category: 'work',
    iconId: 'coffee',
    attendees: 6,
    confirmedAttendees: 4,
    location: 'Downtown Café',
    description: 'Casual coworking session with coffee.',
    hasVoting: false,
    hasTasks: false,
    hasPayment: false,
    organizerId: 'me',
    organizerName: 'Andor',
    status: 'fixed',
    participants: [
      { id: '1', name: 'Bugs Bunny', status: 'confirmed' },
      { id: '2', name: 'Lisa Simpson', status: 'confirmed' },
    ],
  },
  {
    id: 18,
    title: 'Concert in the Park',
    date: '2026-03-22',
    time: '18:00',
    type: 'public',
    category: 'friends',
    iconId: 'music',
    attendees: 150,
    confirmedAttendees: 90,
    location: 'City Park Amphitheater',
    description: 'Local bands and food trucks.',
    hasVoting: true,
    hasTasks: false,
    hasPayment: true,
    paymentAmount: 25,
    currency: 'EUR',
    organizerId: 'mickey',
    organizerName: 'Mickey Mouse',
    status: 'in-progress',
    participants: [
      { id: 'me', name: 'Me', status: 'confirmed' },
      { id: '1', name: 'Goofy', status: 'confirmed' },
    ],
  },
  {
    id: 19,
    title: 'Beach Picnic',
    date: '2026-04-05',
    time: '11:00',
    type: 'public',
    category: 'family',
    iconId: 'picnic',
    attendees: 12,
    confirmedAttendees: 8,
    location: 'Sunset Beach',
    description: 'Potluck picnic by the sea.',
    hasVoting: true,
    hasTasks: true,
    hasPayment: false,
    organizerId: 'sponge',
    organizerName: 'SpongeBob SquarePants',
    status: 'optimal',
    participants: [
      { id: 'me', name: 'Me', status: 'pending' },
      { id: '1', name: 'Patrick Star', status: 'confirmed' },
      { id: '2', name: 'Sandy Cheeks', status: 'confirmed' },
    ],
  },
  {
    id: 20,
    title: 'Yoga in the Park',
    date: '2026-04-12',
    time: '08:00',
    type: 'public',
    category: 'sports',
    iconId: 'yoga',
    attendees: 20,
    confirmedAttendees: 14,
    location: 'Central Park Lawn',
    description: 'Morning yoga session for all levels.',
    hasVoting: false,
    hasTasks: false,
    hasPayment: true,
    paymentAmount: 10,
    currency: 'EUR',
    organizerId: 'diana',
    organizerName: 'Wonder Woman',
    status: 'in-progress',
    participants: [
      { id: 'me', name: 'Me', status: 'confirmed' },
      { id: '1', name: 'Batman', status: 'pending' },
    ],
  },
  {
    id: 21,
    title: 'Running Club Meetup',
    date: '2026-03-08',
    time: '07:30',
    type: 'public',
    category: 'sports',
    iconId: 'running',
    attendees: 25,
    confirmedAttendees: 18,
    location: 'Riverside Trail',
    description: '5K group run along the river.',
    hasVoting: false,
    hasTasks: false,
    hasPayment: false,
    organizerId: 'daffy',
    organizerName: 'Daffy Duck',
    status: 'fixed',
    participants: [
      { id: '1', name: 'Bugs Bunny', status: 'confirmed' },
      { id: '2', name: 'Tweety', status: 'confirmed' },
    ],
  },
  {
    id: 22,
    title: 'Photography Walk',
    date: '2026-03-29',
    time: '15:00',
    type: 'public',
    category: 'work',
    iconId: 'workshop',
    attendees: 15,
    confirmedAttendees: 10,
    location: 'Old Town District',
    description: 'Street photography tour with tips from pros.',
    hasVoting: false,
    hasTasks: false,
    hasPayment: true,
    paymentAmount: 15,
    currency: 'EUR',
    organizerId: 'elastigirl',
    organizerName: 'Elastigirl',
    status: 'optimal',
    participants: [{ id: '1', name: 'Mr. Incredible', status: 'confirmed' }],
  },
  {
    id: 23,
    title: 'Karaoke Night',
    date: '2026-04-18',
    time: '20:00',
    type: 'public',
    category: 'friends',
    iconId: 'party',
    attendees: 40,
    confirmedAttendees: 25,
    location: 'Downtown Bar',
    description: 'Sing your heart out! Song requests welcome.',
    hasVoting: false,
    hasTasks: false,
    hasPayment: false,
    organizerId: 'snoopy',
    organizerName: 'Snoopy',
    status: 'in-progress',
    participants: [
      { id: '1', name: 'Charlie Brown', status: 'confirmed' },
      { id: '2', name: 'Lucy van Pelt', status: 'pending' },
    ],
  },
  {
    id: 24,
    title: 'Trivia Night',
    date: '2026-04-25',
    time: '19:00',
    type: 'public',
    category: 'friends',
    iconId: 'gaming',
    attendees: 30,
    confirmedAttendees: 22,
    location: 'The Pub',
    description: 'Team trivia with prizes. Form your squad!',
    hasVoting: false,
    hasTasks: false,
    hasPayment: true,
    paymentAmount: 5,
    currency: 'EUR',
    organizerId: 'brian',
    organizerName: 'Brian Griffin',
    status: 'fixed',
    participants: [
      { id: '1', name: 'Peter Griffin', status: 'confirmed' },
      { id: '2', name: 'Stewie Griffin', status: 'confirmed' },
    ],
  },
  {
    id: 25,
    title: 'Flea Market Sunday',
    date: '2026-05-03',
    time: '09:00',
    type: 'public',
    category: 'friends',
    iconId: 'party',
    attendees: 80,
    confirmedAttendees: 45,
    location: 'Main Square',
    description:
      'Community flea market. Bring stuff to sell or just browse!',
    hasVoting: false,
    hasTasks: true,
    hasPayment: false,
    organizerId: 'walle',
    organizerName: 'WALL-E',
    status: 'in-progress',
    participants: [{ id: '1', name: 'EVE', status: 'confirmed' }],
  },
  {
    id: 26,
    title: 'Halloween Party',
    date: '2026-10-31',
    time: '19:00',
    type: 'private',
    category: 'friends',
    iconId: 'halloween',
    attendees: 12,
    confirmedAttendees: 8,
    location: 'My Place',
    description: 'Spooky Halloween get-together with costumes and treats.',
    hasVoting: true,
    hasTasks: true,
    hasPayment: false,
    organizerId: 'me',
    organizerName: 'Andor',
    status: 'optimal',
    participants: [
      { id: '1', name: 'Homer Simpson', status: 'confirmed' },
      { id: '2', name: 'Marge Simpson', status: 'pending' },
    ],
  },
  {
    id: 27,
    title: 'October Meetup',
    date: '2026-10-15',
    time: '18:00',
    type: 'public',
    category: 'friends',
    iconId: 'coffee',
    attendees: 10,
    confirmedAttendees: 6,
    location: 'Downtown Café',
    description: 'Monthly coffee and catch-up.',
    hasVoting: false,
    hasTasks: false,
    hasPayment: false,
    organizerId: 'me',
    organizerName: 'Andor',
    status: 'in-progress',
  },
  {
    id: 28,
    title: 'Autumn Hike',
    date: '2026-10-08',
    time: '09:00',
    type: 'public',
    category: 'sports',
    iconId: 'hiking',
    attendees: 8,
    confirmedAttendees: 5,
    location: 'Normafa',
    description: 'Enjoy the fall colors on the trails.',
    hasVoting: true,
    hasTasks: true,
    hasPayment: false,
    organizerId: 'me',
    organizerName: 'Andor',
    status: 'optimal',
  },
]
