// Demo events data - like RAZ template seed data

import type { Event } from './types'

export const demoEvents: Event[] = [
  {
    id: 1,
    title: 'Summer BBQ Party',
    date: '2025-01-15',
    time: '18:00',
    type: 'public',
    category: 'friends',
    iconId: 'bbq',
    attendees: 24,
    confirmedAttendees: 24,
    location: 'Central Park',
    description:
      'Annual summer BBQ with games, music, and great food. Bring your own drinks!',
    hasVoting: false,
    hasTasks: true,
    hasPayment: false,
    organizerId: 'me',
    organizerName: 'Andor',
    status: 'fixed',
    tasks: [
      { id: 1, title: 'Buy charcoal', completed: true, assignee: 'Homer' },
      { id: 2, title: 'Setup tables', completed: true, assignee: 'Charlie Brown' },
      { id: 3, title: 'Prepare playlist', completed: true, assignee: 'Me' },
    ],
    participants: [
      { id: '1', name: 'Homer Simpson', status: 'confirmed' },
      { id: '2', name: 'Charlie Brown', status: 'confirmed' },
      { id: '3', name: 'SpongeBob SquarePants', status: 'confirmed' },
    ],
    resources: [
      {
        id: '1',
        type: 'drive',
        name: 'Event Planning',
        url: 'https://drive.google.com/folder',
      },
      {
        id: '2',
        type: 'photos',
        name: 'BBQ Photos',
        url: 'https://photos.google.com/album',
      },
    ],
    sharedDrive: 'https://drive.google.com',
    photos: 'https://photos.google.com',
  },
  {
    id: 2,
    title: 'Birthday Celebration',
    date: '2025-01-28',
    time: '19:00',
    type: 'private',
    category: 'friends',
    iconId: 'birthday',
    attendees: 15,
    confirmedAttendees: 12,
    location: 'My Place',
    description: 'Turning 30! Come celebrate with cake, drinks, and good vibes.',
    hasVoting: true,
    hasTasks: true,
    hasPayment: false,
    organizerId: 'me',
    organizerName: 'Andor',
    status: 'in-progress',
    tasks: [
      { id: 1, title: 'Order cake', completed: true },
      { id: 2, title: 'Send invites', completed: true },
      { id: 3, title: 'Buy decorations', completed: false },
    ],
    participants: [
      { id: '1', name: 'Marge Simpson', status: 'confirmed' },
      { id: '2', name: 'Bart Simpson', status: 'confirmed' },
      { id: '3', name: 'Lisa Simpson', status: 'pending' },
    ],
  },
  {
    id: 3,
    title: 'Weekend Ski Trip',
    date: '2025-02-08',
    time: '07:00',
    type: 'private',
    category: 'sports',
    iconId: 'ski',
    attendees: 6,
    confirmedAttendees: 4,
    location: 'Alpine Resort',
    description: 'Two days of skiing and relaxation in the mountains.',
    hasVoting: true,
    hasTasks: true,
    hasPayment: true,
    paymentAmount: 180,
    currency: 'EUR',
    organizerId: 'me',
    organizerName: 'Andor',
    status: 'optimal',
    tasks: [
      { id: 1, title: 'Book accommodation', completed: true },
      { id: 2, title: 'Rent equipment', completed: false },
      { id: 3, title: 'Arrange transport', completed: false },
    ],
    participants: [
      { id: '1', name: 'Patrick Star', status: 'confirmed' },
      { id: '2', name: 'Sandy Cheeks', status: 'confirmed' },
      { id: '3', name: 'Squidward Tentacles', status: 'pending' },
    ],
  },
  {
    id: 4,
    title: 'Game Night',
    date: '2025-01-18',
    time: '20:00',
    type: 'private',
    category: 'friends',
    iconId: 'gaming',
    attendees: 8,
    confirmedAttendees: 8,
    location: 'My Apartment',
    description: 'Board games, video games, snacks, and fun!',
    hasVoting: false,
    hasTasks: false,
    hasPayment: false,
    organizerId: 'me',
    organizerName: 'Andor',
    status: 'fixed',
    participants: [
      { id: '1', name: 'Mickey Mouse', status: 'confirmed' },
      { id: '2', name: 'Donald Duck', status: 'confirmed' },
      { id: '3', name: 'Goofy', status: 'confirmed' },
      { id: '4', name: 'Minnie Mouse', status: 'confirmed' },
    ],
  },
  {
    id: 13,
    title: 'Normafa IV.',
    date: '2026-02-23',
    time: '09:00',
    type: 'public',
    category: 'sports',
    iconId: 'hiking',
    attendees: 12,
    confirmedAttendees: 6,
    location: 'Budapest, Normafa',
    description: 'Group hike to Normafa, then coffee at the cabin.',
    hasVoting: true,
    hasTasks: true,
    hasPayment: false,
    organizerId: 'scooby',
    organizerName: 'Scooby-Doo',
    status: 'in-progress',
    tasks: [
      { id: 1, title: 'Check weather', completed: false },
      { id: 2, title: 'Share meetup point', completed: true },
    ],
    participants: [
      { id: 'me', name: 'Me', status: 'pending' },
      { id: '1', name: 'Shaggy Rogers', status: 'pending' },
      { id: '2', name: 'Velma Dinkley', status: 'confirmed' },
    ],
  },
  {
    id: 14,
    title: 'Team Offsite Q1',
    date: '2026-02-18',
    time: '10:00',
    type: 'private',
    category: 'work',
    iconId: 'meeting',
    attendees: 14,
    confirmedAttendees: 10,
    location: 'Office Conference Room A',
    description: 'Quarterly planning and team building.',
    hasVoting: true,
    hasTasks: true,
    hasPayment: false,
    organizerId: 'me',
    organizerName: 'Andor',
    status: 'optimal',
    participants: [
      { id: '1', name: 'Bugs Bunny', status: 'confirmed' },
      { id: '2', name: 'Daffy Duck', status: 'pending' },
    ],
  },
  {
    id: 15,
    title: 'Pizza Night',
    date: '2026-02-16',
    time: '19:00',
    type: 'private',
    category: 'friends',
    iconId: 'dinner',
    attendees: 6,
    confirmedAttendees: 4,
    location: 'Downtown Pizzeria',
    description: 'Casual get-together with pizza and drinks.',
    hasVoting: true,
    hasTasks: false,
    hasPayment: true,
    paymentAmount: 15,
    currency: 'EUR',
    organizerId: 'lisa',
    organizerName: 'Lisa Simpson',
    status: 'in-progress',
    participants: [
      { id: 'me', name: 'Me', status: 'confirmed' },
      { id: '1', name: 'Bart Simpson', status: 'confirmed' },
    ],
  },
  {
    id: 5,
    title: 'Family Reunion',
    date: '2025-01-20',
    time: '14:00',
    type: 'private',
    category: 'family',
    iconId: 'family',
    attendees: 25,
    confirmedAttendees: 18,
    location: "Grandma's House",
    description: 'Annual family gathering with dinner and catching up.',
    hasVoting: true,
    hasTasks: true,
    hasPayment: false,
    organizerId: 'marge',
    organizerName: 'Marge Simpson',
    status: 'optimal',
    tasks: [
      { id: 1, title: 'Send invitations', completed: true },
      { id: 2, title: 'Plan menu', completed: false },
    ],
    participants: [
      { id: 'me', name: 'Me', status: 'confirmed' },
      { id: '2', name: 'Abe Simpson', status: 'pending' },
      { id: '3', name: 'Maggie Simpson', status: 'confirmed' },
    ],
  },
  {
    id: 6,
    title: 'Tech Conference 2025',
    date: '2025-01-25',
    time: '09:00',
    type: 'public',
    category: 'work',
    iconId: 'work',
    attendees: 320,
    confirmedAttendees: 180,
    location: 'Convention Center',
    description: 'Annual tech conference featuring talks from industry leaders.',
    hasVoting: true,
    hasTasks: true,
    hasPayment: true,
    paymentAmount: 299,
    currency: 'USD',
    organizerId: 'homer',
    organizerName: 'Homer Simpson',
    status: 'in-progress',
    tasks: [
      { id: 1, title: 'Book speakers', completed: true },
      { id: 2, title: 'Setup registration', completed: true },
      { id: 3, title: 'Print badges', completed: false },
    ],
    participants: [
      { id: 'me', name: 'Me', status: 'confirmed' },
      { id: '2', name: 'Mr. Burns', status: 'confirmed' },
      { id: '3', name: 'Lenny Leonard', status: 'pending' },
    ],
    sharedDrive: 'https://drive.google.com',
    documents: 'https://docs.google.com',
  },
  {
    id: 7,
    title: 'Wedding Celebration',
    date: '2025-02-14',
    time: '16:00',
    type: 'private',
    category: 'family',
    iconId: 'wedding',
    attendees: 150,
    confirmedAttendees: 150,
    location: 'Garden Venue',
    description: 'Join us for our special day!',
    hasVoting: false,
    hasTasks: false,
    hasPayment: false,
    organizerId: 'homer',
    organizerName: 'Homer & Marge',
    status: 'fixed',
    participants: [
      { id: 'me', name: 'Me', status: 'confirmed' },
      { id: '2', name: 'Marge Simpson', status: 'confirmed' },
    ],
    resources: [
      {
        id: '1',
        type: 'photos',
        name: 'Wedding Album',
        url: 'https://photos.google.com/album',
      },
    ],
    photos: 'https://photos.google.com',
  },
  {
    id: 8,
    title: 'Hiking Adventure',
    date: '2025-02-01',
    time: '08:00',
    type: 'public',
    category: 'sports',
    iconId: 'hiking',
    attendees: 12,
    confirmedAttendees: 8,
    location: 'Mountain Trail',
    description: 'Day hike to the summit with experienced guides.',
    hasVoting: false,
    hasTasks: true,
    hasPayment: true,
    paymentAmount: 25,
    currency: 'EUR',
    organizerId: 'charlie',
    organizerName: 'Charlie Brown',
    status: 'in-progress',
    tasks: [
      {
        id: 1,
        title: 'Check weather',
        completed: false,
        assignee: 'Charlie Brown',
      },
      { id: 2, title: 'Pack supplies', completed: false, assignee: 'Snoopy' },
    ],
    participants: [
      { id: 'me', name: 'Me', status: 'confirmed' },
      { id: '2', name: 'Snoopy', status: 'confirmed' },
      { id: '3', name: 'Lucy van Pelt', status: 'pending' },
    ],
  },
  {
    id: 9,
    title: 'Wine Tasting Evening',
    date: '2025-02-05',
    time: '19:00',
    type: 'private',
    category: 'friends',
    iconId: 'dinner',
    attendees: 10,
    confirmedAttendees: 7,
    location: 'Wine Bar Downtown',
    description: 'An evening of fine wines and good conversation.',
    hasVoting: true,
    hasTasks: false,
    hasPayment: true,
    paymentAmount: 45,
    currency: 'EUR',
    organizerId: 'diana',
    organizerName: 'Wonder Woman',
    status: 'optimal',
    participants: [
      { id: 'me', name: 'Me', status: 'confirmed' },
      { id: '2', name: 'Batman', status: 'confirmed' },
      { id: '3', name: 'Superman', status: 'pending' },
    ],
  },
  {
    id: 10,
    title: 'Charity Fundraiser',
    date: '2025-02-20',
    time: '19:00',
    type: 'public',
    category: 'work',
    iconId: 'party',
    attendees: 200,
    confirmedAttendees: 85,
    location: 'Grand Hotel',
    description: 'Annual charity gala to support local initiatives.',
    hasVoting: true,
    hasTasks: true,
    hasPayment: true,
    paymentAmount: 50,
    currency: 'EUR',
    organizerId: 'edna',
    organizerName: 'Edna Mode',
    status: 'in-progress',
    tasks: [
      { id: 1, title: 'Contact sponsors', completed: true, assignee: 'Edna' },
      {
        id: 2,
        title: 'Arrange catering',
        completed: false,
        assignee: 'Wonder Woman',
      },
    ],
    participants: [
      { id: 'me', name: 'Me', status: 'confirmed' },
      { id: '2', name: 'Elastigirl', status: 'confirmed' },
    ],
    sharedDrive: 'https://drive.google.com',
    documents: 'https://docs.google.com',
  },
  {
    id: 11,
    title: 'Book Club Meeting',
    date: '2025-01-22',
    time: '18:30',
    type: 'private',
    category: 'friends',
    iconId: 'coffee',
    attendees: 8,
    confirmedAttendees: 6,
    location: 'Coffee House',
    description: 'Discussing "The Great Gatsby" this month.',
    hasVoting: false,
    hasTasks: false,
    hasPayment: false,
    organizerId: 'grace',
    organizerName: 'Minnie Mouse',
    status: 'fixed',
    participants: [
      { id: 'me', name: 'Me', status: 'confirmed' },
      { id: '2', name: 'Daisy Duck', status: 'confirmed' },
      { id: '3', name: 'Pluto', status: 'confirmed' },
    ],
  },
  {
    id: 12,
    title: 'Beach Volleyball Tournament',
    date: '2025-02-15',
    time: '10:00',
    type: 'public',
    category: 'sports',
    iconId: 'beach',
    attendees: 32,
    confirmedAttendees: 24,
    location: 'Sunset Beach',
    description: 'Friendly tournament with teams of 4. Prizes for winners!',
    hasVoting: true,
    hasTasks: true,
    hasPayment: true,
    paymentAmount: 15,
    currency: 'EUR',
    organizerId: 'peter',
    organizerName: 'Peter Griffin',
    status: 'in-progress',
    tasks: [
      { id: 1, title: 'Reserve beach area', completed: true },
      { id: 2, title: 'Get nets and balls', completed: true },
      { id: 3, title: 'Organize teams', completed: false },
    ],
    participants: [
      { id: 'me', name: 'Me', status: 'pending' },
      { id: '2', name: 'Lois Griffin', status: 'confirmed' },
      { id: '3', name: 'Stewie Griffin', status: 'confirmed' },
    ],
  },
  {
    id: 16,
    title: 'Camping Weekend',
    date: '2026-03-15',
    time: '14:00',
    type: 'public',
    category: 'sports',
    iconId: 'camping',
    attendees: 8,
    confirmedAttendees: 5,
    location: 'Lake Balaton',
    description: 'Two nights under the stars. Bring your tent!',
    hasVoting: true,
    hasTasks: true,
    hasPayment: true,
    paymentAmount: 20,
    currency: 'EUR',
    organizerId: 'me',
    organizerName: 'Andor',
    status: 'optimal',
    participants: [
      { id: '1', name: 'Patrick Star', status: 'confirmed' },
      { id: '2', name: 'Shaggy Rogers', status: 'pending' },
    ],
  },
  {
    id: 17,
    title: 'Coffee & Code Morning',
    date: '2026-03-01',
    time: '09:00',
    type: 'private',
    category: 'work',
    iconId: 'coffee',
    attendees: 6,
    confirmedAttendees: 4,
    location: 'Downtown Café',
    description: 'Casual coworking session with coffee.',
    hasVoting: false,
    hasTasks: false,
    hasPayment: false,
    organizerId: 'me',
    organizerName: 'Andor',
    status: 'fixed',
    participants: [
      { id: '1', name: 'Bugs Bunny', status: 'confirmed' },
      { id: '2', name: 'Lisa Simpson', status: 'confirmed' },
    ],
  },
  {
    id: 18,
    title: 'Concert in the Park',
    date: '2026-03-22',
    time: '18:00',
    type: 'public',
    category: 'friends',
    iconId: 'music',
    attendees: 150,
    confirmedAttendees: 90,
    location: 'City Park Amphitheater',
    description: 'Local bands and food trucks.',
    hasVoting: true,
    hasTasks: false,
    hasPayment: true,
    paymentAmount: 25,
    currency: 'EUR',
    organizerId: 'mickey',
    organizerName: 'Mickey Mouse',
    status: 'in-progress',
    participants: [
      { id: 'me', name: 'Me', status: 'confirmed' },
      { id: '1', name: 'Goofy', status: 'confirmed' },
    ],
  },
  {
    id: 19,
    title: 'Beach Picnic',
    date: '2026-04-05',
    time: '11:00',
    type: 'public',
    category: 'family',
    iconId: 'picnic',
    attendees: 12,
    confirmedAttendees: 8,
    location: 'Sunset Beach',
    description: 'Potluck picnic by the sea.',
    hasVoting: true,
    hasTasks: true,
    hasPayment: false,
    organizerId: 'sponge',
    organizerName: 'SpongeBob SquarePants',
    status: 'optimal',
    participants: [
      { id: 'me', name: 'Me', status: 'pending' },
      { id: '1', name: 'Patrick Star', status: 'confirmed' },
      { id: '2', name: 'Sandy Cheeks', status: 'confirmed' },
    ],
  },
  {
    id: 20,
    title: 'Yoga in the Park',
    date: '2026-04-12',
    time: '08:00',
    type: 'public',
    category: 'sports',
    iconId: 'yoga',
    attendees: 20,
    confirmedAttendees: 14,
    location: 'Central Park Lawn',
    description: 'Morning yoga session for all levels.',
    hasVoting: false,
    hasTasks: false,
    hasPayment: true,
    paymentAmount: 10,
    currency: 'EUR',
    organizerId: 'diana',
    organizerName: 'Wonder Woman',
    status: 'in-progress',
    participants: [
      { id: 'me', name: 'Me', status: 'confirmed' },
      { id: '1', name: 'Batman', status: 'pending' },
    ],
  },
  {
    id: 21,
    title: 'Running Club Meetup',
    date: '2026-03-08',
    time: '07:30',
    type: 'public',
    category: 'sports',
    iconId: 'running',
    attendees: 25,
    confirmedAttendees: 18,
    location: 'Riverside Trail',
    description: '5K group run along the river.',
    hasVoting: false,
    hasTasks: false,
    hasPayment: false,
    organizerId: 'daffy',
    organizerName: 'Daffy Duck',
    status: 'fixed',
    participants: [
      { id: '1', name: 'Bugs Bunny', status: 'confirmed' },
      { id: '2', name: 'Tweety', status: 'confirmed' },
    ],
  },
  {
    id: 22,
    title: 'Photography Walk',
    date: '2026-03-29',
    time: '15:00',
    type: 'public',
    category: 'work',
    iconId: 'workshop',
    attendees: 15,
    confirmedAttendees: 10,
    location: 'Old Town District',
    description: 'Street photography tour with tips from pros.',
    hasVoting: false,
    hasTasks: false,
    hasPayment: true,
    paymentAmount: 15,
    currency: 'EUR',
    organizerId: 'elastigirl',
    organizerName: 'Elastigirl',
    status: 'optimal',
    participants: [{ id: '1', name: 'Mr. Incredible', status: 'confirmed' }],
  },
  {
    id: 23,
    title: 'Karaoke Night',
    date: '2026-04-18',
    time: '20:00',
    type: 'public',
    category: 'friends',
    iconId: 'party',
    attendees: 40,
    confirmedAttendees: 25,
    location: 'Downtown Bar',
    description: 'Sing your heart out! Song requests welcome.',
    hasVoting: false,
    hasTasks: false,
    hasPayment: false,
    organizerId: 'snoopy',
    organizerName: 'Snoopy',
    status: 'in-progress',
    participants: [
      { id: '1', name: 'Charlie Brown', status: 'confirmed' },
      { id: '2', name: 'Lucy van Pelt', status: 'pending' },
    ],
  },
  {
    id: 24,
    title: 'Trivia Night',
    date: '2026-04-25',
    time: '19:00',
    type: 'public',
    category: 'friends',
    iconId: 'gaming',
    attendees: 30,
    confirmedAttendees: 22,
    location: 'The Pub',
    description: 'Team trivia with prizes. Form your squad!',
    hasVoting: false,
    hasTasks: false,
    hasPayment: true,
    paymentAmount: 5,
    currency: 'EUR',
    organizerId: 'brian',
    organizerName: 'Brian Griffin',
    status: 'fixed',
    participants: [
      { id: '1', name: 'Peter Griffin', status: 'confirmed' },
      { id: '2', name: 'Stewie Griffin', status: 'confirmed' },
    ],
  },
  {
    id: 25,
    title: 'Flea Market Sunday',
    date: '2026-05-03',
    time: '09:00',
    type: 'public',
    category: 'friends',
    iconId: 'party',
    attendees: 80,
    confirmedAttendees: 45,
    location: 'Main Square',
    description:
      'Community flea market. Bring stuff to sell or just browse!',
    hasVoting: false,
    hasTasks: true,
    hasPayment: false,
    organizerId: 'walle',
    organizerName: 'WALL-E',
    status: 'in-progress',
    participants: [{ id: '1', name: 'EVE', status: 'confirmed' }],
  },
  {
    id: 26,
    title: 'Halloween Party',
    date: '2026-10-31',
    time: '19:00',
    type: 'private',
    category: 'friends',
    iconId: 'halloween',
    attendees: 12,
    confirmedAttendees: 8,
    location: 'My Place',
    description: 'Spooky Halloween get-together with costumes and treats.',
    hasVoting: true,
    hasTasks: true,
    hasPayment: false,
    organizerId: 'me',
    organizerName: 'Andor',
    status: 'optimal',
    participants: [
      { id: '1', name: 'Homer Simpson', status: 'confirmed' },
      { id: '2', name: 'Marge Simpson', status: 'pending' },
    ],
  },
  {
    id: 27,
    title: 'October Meetup',
    date: '2026-10-15',
    time: '18:00',
    type: 'public',
    category: 'friends',
    iconId: 'coffee',
    attendees: 10,
    confirmedAttendees: 6,
    location: 'Downtown Café',
    description: 'Monthly coffee and catch-up.',
    hasVoting: false,
    hasTasks: false,
    hasPayment: false,
    organizerId: 'me',
    organizerName: 'Andor',
    status: 'in-progress',
  },
  {
    id: 28,
    title: 'Autumn Hike',
    date: '2026-10-08',
    time: '09:00',
    type: 'public',
    category: 'sports',
    iconId: 'hiking',
    attendees: 8,
    confirmedAttendees: 5,
    location: 'Normafa',
    description: 'Enjoy the fall colors on the trails.',
    hasVoting: true,
    hasTasks: true,
    hasPayment: false,
    organizerId: 'me',
    organizerName: 'Andor',
    status: 'optimal',
  },
  // === My Events (organizerId: 'me') with category 'none' ===
  {
    id: 29,
    title: 'Craft Beer Tasting',
    date: '2026-02-21',
    time: '18:30',
    type: 'private',
    category: 'none',
    iconId: 'dinner',
    attendees: 10,
    confirmedAttendees: 7,
    location: 'Hop House Brewery',
    description: 'Sampling local craft beers with guided tasting notes.',
    hasVoting: true,
    hasTasks: true,
    hasPayment: true,
    paymentAmount: 20,
    currency: 'EUR',
    organizerId: 'me',
    organizerName: 'Andor',
    status: 'in-progress',
    tasks: [
      { id: 1, title: 'Reserve tasting room', completed: true, assignee: 'Me' },
      { id: 2, title: 'Print tasting cards', completed: false, assignee: 'Shaggy Rogers' },
    ],
    participants: [
      { id: '1', name: 'Shaggy Rogers', status: 'confirmed' },
      { id: '2', name: 'Fred Flintstone', status: 'confirmed' },
      { id: '3', name: 'Barney Rubble', status: 'pending' },
    ],
  },
  {
    id: 30,
    title: 'Movie Marathon Night',
    date: '2026-03-07',
    time: '17:00',
    type: 'private',
    category: 'none',
    iconId: 'movie',
    attendees: 8,
    confirmedAttendees: 8,
    location: 'My Living Room',
    description: 'Back-to-back sci-fi classics. Popcorn provided!',
    hasVoting: true,
    hasTasks: false,
    hasPayment: false,
    organizerId: 'me',
    organizerName: 'Andor',
    status: 'fixed',
    participants: [
      { id: '1', name: 'Bugs Bunny', status: 'confirmed' },
      { id: '2', name: 'Daffy Duck', status: 'confirmed' },
      { id: '3', name: 'Tweety', status: 'confirmed' },
      { id: '4', name: 'Sylvester', status: 'confirmed' },
    ],
  },
  {
    id: 31,
    title: 'Language Exchange Meetup',
    date: '2026-03-14',
    time: '10:00',
    type: 'public',
    category: 'none',
    iconId: 'coffee',
    attendees: 16,
    confirmedAttendees: 10,
    location: 'Community Library',
    description: 'Practice languages over coffee. All levels welcome!',
    hasVoting: false,
    hasTasks: true,
    hasPayment: false,
    organizerId: 'me',
    organizerName: 'Andor',
    status: 'optimal',
    tasks: [
      { id: 1, title: 'Book meeting room', completed: true },
      { id: 2, title: 'Create name tags', completed: false, assignee: 'Dora' },
    ],
    participants: [
      { id: '1', name: 'Dora the Explorer', status: 'confirmed' },
      { id: '2', name: 'Dexter', status: 'confirmed' },
      { id: '3', name: 'Johnny Bravo', status: 'pending' },
    ],
  },
  {
    id: 32,
    title: 'Rooftop Stargazing',
    date: '2026-04-10',
    time: '21:00',
    type: 'private',
    category: 'none',
    iconId: 'calendar',
    attendees: 6,
    confirmedAttendees: 4,
    location: 'Rooftop Terrace, Downtown',
    description: 'Telescopes and hot cocoa under the stars.',
    hasVoting: false,
    hasTasks: true,
    hasPayment: false,
    organizerId: 'me',
    organizerName: 'Andor',
    status: 'in-progress',
    tasks: [
      { id: 1, title: 'Borrow telescope', completed: true, assignee: 'Dexter' },
      { id: 2, title: 'Make hot cocoa', completed: false, assignee: 'Me' },
    ],
    participants: [
      { id: '1', name: 'Dexter', status: 'confirmed' },
      { id: '2', name: 'Jimmy Neutron', status: 'confirmed' },
      { id: '3', name: 'Velma Dinkley', status: 'pending' },
    ],
  },
  {
    id: 33,
    title: 'Vintage Car Show',
    date: '2026-05-09',
    time: '10:00',
    type: 'public',
    category: 'none',
    iconId: 'trip',
    attendees: 50,
    confirmedAttendees: 35,
    location: 'Exhibition Grounds',
    description: 'Admire classic rides and meet fellow enthusiasts.',
    hasVoting: true,
    hasTasks: true,
    hasPayment: true,
    paymentAmount: 8,
    currency: 'EUR',
    organizerId: 'me',
    organizerName: 'Andor',
    status: 'optimal',
    tasks: [
      { id: 1, title: 'Secure venue permit', completed: true },
      { id: 2, title: 'Contact car clubs', completed: true, assignee: 'Speed Racer' },
      { id: 3, title: 'Print flyers', completed: false },
    ],
    participants: [
      { id: '1', name: 'Speed Racer', status: 'confirmed' },
      { id: '2', name: 'Lightning McQueen', status: 'confirmed' },
      { id: '3', name: 'Mater', status: 'confirmed' },
    ],
  },
  {
    id: 34,
    title: 'Board Game Tournament',
    date: '2026-05-16',
    time: '14:00',
    type: 'private',
    category: 'none',
    iconId: 'gaming',
    attendees: 12,
    confirmedAttendees: 12,
    location: 'Game Café',
    description: 'Competitive board gaming with bracket-style tournament.',
    hasVoting: false,
    hasTasks: false,
    hasPayment: true,
    paymentAmount: 5,
    currency: 'EUR',
    organizerId: 'me',
    organizerName: 'Andor',
    status: 'fixed',
    participants: [
      { id: '1', name: 'Tom', status: 'confirmed' },
      { id: '2', name: 'Jerry', status: 'confirmed' },
      { id: '3', name: 'Garfield', status: 'confirmed' },
      { id: '4', name: 'Odie', status: 'confirmed' },
    ],
  },
  {
    id: 35,
    title: 'Potluck Dinner Party',
    date: '2026-06-06',
    time: '19:00',
    type: 'private',
    category: 'none',
    iconId: 'dinner',
    attendees: 10,
    confirmedAttendees: 8,
    location: 'My Apartment',
    description: 'Everyone brings a dish. Theme: international cuisine!',
    hasVoting: true,
    hasTasks: true,
    hasPayment: false,
    organizerId: 'me',
    organizerName: 'Andor',
    status: 'in-progress',
    tasks: [
      { id: 1, title: 'Set up dining table', completed: false, assignee: 'Me' },
      { id: 2, title: 'Create dish sign-up sheet', completed: true },
    ],
    participants: [
      { id: '1', name: 'Remy the Rat', status: 'confirmed' },
      { id: '2', name: 'SpongeBob SquarePants', status: 'confirmed' },
      { id: '3', name: 'Popeye', status: 'pending' },
    ],
  },
  {
    id: 36,
    title: 'Escape Room Challenge',
    date: '2026-06-20',
    time: '16:00',
    type: 'private',
    category: 'none',
    iconId: 'gaming',
    attendees: 6,
    confirmedAttendees: 6,
    location: 'Mystery Rooms Downtown',
    description: 'Can we escape in under 60 minutes? Let\'s find out!',
    hasVoting: false,
    hasTasks: false,
    hasPayment: true,
    paymentAmount: 25,
    currency: 'EUR',
    organizerId: 'me',
    organizerName: 'Andor',
    status: 'fixed',
    participants: [
      { id: '1', name: 'Scooby-Doo', status: 'confirmed' },
      { id: '2', name: 'Shaggy Rogers', status: 'confirmed' },
      { id: '3', name: 'Velma Dinkley', status: 'confirmed' },
      { id: '4', name: 'Fred Jones', status: 'confirmed' },
      { id: '5', name: 'Daphne Blake', status: 'confirmed' },
    ],
  },
  {
    id: 37,
    title: 'Dog Park Hangout',
    date: '2026-07-04',
    time: '10:00',
    type: 'public',
    category: 'none',
    iconId: 'calendar',
    attendees: 15,
    confirmedAttendees: 9,
    location: 'Riverside Dog Park',
    description: 'Bring your pups for a playdate and socializing.',
    hasVoting: false,
    hasTasks: false,
    hasPayment: false,
    organizerId: 'me',
    organizerName: 'Andor',
    status: 'optimal',
    participants: [
      { id: '1', name: 'Snoopy', status: 'confirmed' },
      { id: '2', name: 'Pluto', status: 'confirmed' },
      { id: '3', name: 'Goofy', status: 'pending' },
    ],
  },
  {
    id: 38,
    title: 'Sunrise Photography Walk',
    date: '2026-07-18',
    time: '05:30',
    type: 'public',
    category: 'none',
    iconId: 'workshop',
    attendees: 8,
    confirmedAttendees: 5,
    location: 'Fisherman\'s Bastion',
    description: 'Capture the golden hour. Bring your camera or phone!',
    hasVoting: false,
    hasTasks: true,
    hasPayment: false,
    organizerId: 'me',
    organizerName: 'Andor',
    status: 'in-progress',
    tasks: [
      { id: 1, title: 'Scout locations', completed: true, assignee: 'Me' },
      { id: 2, title: 'Share tips sheet', completed: false },
    ],
    participants: [
      { id: '1', name: 'Tintin', status: 'confirmed' },
      { id: '2', name: 'Captain Haddock', status: 'pending' },
    ],
  },
  {
    id: 39,
    title: 'DIY Candle Making',
    date: '2026-08-01',
    time: '15:00',
    type: 'private',
    category: 'none',
    iconId: 'workshop',
    attendees: 8,
    confirmedAttendees: 6,
    location: 'Maker Space',
    description: 'Learn to make scented candles. All supplies provided.',
    hasVoting: false,
    hasTasks: true,
    hasPayment: true,
    paymentAmount: 18,
    currency: 'EUR',
    organizerId: 'me',
    organizerName: 'Andor',
    status: 'optimal',
    tasks: [
      { id: 1, title: 'Buy wax and wicks', completed: true, assignee: 'Me' },
      { id: 2, title: 'Get essential oils', completed: false, assignee: 'Rapunzel' },
    ],
    participants: [
      { id: '1', name: 'Rapunzel', status: 'confirmed' },
      { id: '2', name: 'Elsa', status: 'confirmed' },
      { id: '3', name: 'Anna', status: 'pending' },
    ],
  },
  {
    id: 40,
    title: 'Open Mic Night',
    date: '2026-08-22',
    time: '20:00',
    type: 'public',
    category: 'none',
    iconId: 'music',
    attendees: 40,
    confirmedAttendees: 28,
    location: 'The Jazz Cellar',
    description: 'Share your talent! Singing, comedy, poetry - all welcome.',
    hasVoting: true,
    hasTasks: false,
    hasPayment: false,
    organizerId: 'me',
    organizerName: 'Andor',
    status: 'in-progress',
    participants: [
      { id: '1', name: 'Josie', status: 'confirmed' },
      { id: '2', name: 'Alvin', status: 'confirmed' },
      { id: '3', name: 'Simon', status: 'confirmed' },
      { id: '4', name: 'Theodore', status: 'pending' },
    ],
  },
  {
    id: 41,
    title: 'Art Gallery Visit',
    date: '2026-09-05',
    time: '11:00',
    type: 'public',
    category: 'none',
    iconId: 'trip',
    attendees: 10,
    confirmedAttendees: 7,
    location: 'Museum of Fine Arts',
    description: 'Guided tour of the new contemporary exhibition.',
    hasVoting: false,
    hasTasks: false,
    hasPayment: true,
    paymentAmount: 12,
    currency: 'EUR',
    organizerId: 'me',
    organizerName: 'Andor',
    status: 'fixed',
    participants: [
      { id: '1', name: 'Lisa Simpson', status: 'confirmed' },
      { id: '2', name: 'Squidward Tentacles', status: 'confirmed' },
      { id: '3', name: 'Bob Ross Jr.', status: 'confirmed' },
    ],
  },
  // === Invited Events (organized by cartoon characters) with category 'none' ===
  {
    id: 42,
    title: 'Bowling League Night',
    date: '2026-02-28',
    time: '19:00',
    type: 'public',
    category: 'none',
    iconId: 'sports',
    attendees: 20,
    confirmedAttendees: 16,
    location: 'Bedrock Lanes',
    description: 'Weekly bowling league. Yabba dabba doo!',
    hasVoting: false,
    hasTasks: false,
    hasPayment: true,
    paymentAmount: 10,
    currency: 'EUR',
    organizerId: 'fred_f',
    organizerName: 'Fred Flintstone',
    status: 'fixed',
    participants: [
      { id: 'me', name: 'Me', status: 'confirmed' },
      { id: '1', name: 'Barney Rubble', status: 'confirmed' },
      { id: '2', name: 'Wilma Flintstone', status: 'confirmed' },
    ],
  },
  {
    id: 43,
    title: 'Mystery Dinner Theater',
    date: '2026-03-20',
    time: '19:30',
    type: 'private',
    category: 'none',
    iconId: 'dinner',
    attendees: 12,
    confirmedAttendees: 9,
    location: 'Spooky Mansion',
    description: 'Solve the mystery while enjoying a 3-course meal!',
    hasVoting: true,
    hasTasks: true,
    hasPayment: true,
    paymentAmount: 35,
    currency: 'EUR',
    organizerId: 'scooby',
    organizerName: 'Scooby-Doo',
    status: 'in-progress',
    tasks: [
      { id: 1, title: 'Write mystery script', completed: true, assignee: 'Velma' },
      { id: 2, title: 'Prepare costumes', completed: false, assignee: 'Daphne' },
    ],
    participants: [
      { id: 'me', name: 'Me', status: 'confirmed' },
      { id: '1', name: 'Shaggy Rogers', status: 'confirmed' },
      { id: '2', name: 'Velma Dinkley', status: 'confirmed' },
    ],
  },
  {
    id: 44,
    title: 'Cat & Mouse Chase Run',
    date: '2026-04-15',
    time: '08:00',
    type: 'public',
    category: 'none',
    iconId: 'running',
    attendees: 30,
    confirmedAttendees: 22,
    location: 'City Park Loop',
    description: 'Fun run with obstacle course. Prizes for fastest cat and mouse!',
    hasVoting: false,
    hasTasks: true,
    hasPayment: true,
    paymentAmount: 12,
    currency: 'EUR',
    organizerId: 'tom_cat',
    organizerName: 'Tom Cat',
    status: 'optimal',
    tasks: [
      { id: 1, title: 'Set up obstacles', completed: false, assignee: 'Jerry' },
      { id: 2, title: 'Mark the route', completed: true, assignee: 'Tom' },
    ],
    participants: [
      { id: 'me', name: 'Me', status: 'pending' },
      { id: '1', name: 'Jerry Mouse', status: 'confirmed' },
      { id: '2', name: 'Spike the Dog', status: 'confirmed' },
    ],
  },
  {
    id: 45,
    title: 'Science Fair Showcase',
    date: '2026-05-02',
    time: '10:00',
    type: 'public',
    category: 'none',
    iconId: 'workshop',
    attendees: 60,
    confirmedAttendees: 42,
    location: 'Dexter\'s Lab Convention Hall',
    description: 'See amazing inventions and experiments. Judges needed!',
    hasVoting: true,
    hasTasks: true,
    hasPayment: false,
    organizerId: 'dexter',
    organizerName: 'Dexter',
    status: 'in-progress',
    tasks: [
      { id: 1, title: 'Set up display tables', completed: true },
      { id: 2, title: 'Arrange judging panel', completed: false, assignee: 'Dexter' },
      { id: 3, title: 'Print certificates', completed: false },
    ],
    participants: [
      { id: 'me', name: 'Me', status: 'confirmed' },
      { id: '1', name: 'Jimmy Neutron', status: 'confirmed' },
      { id: '2', name: 'Dee Dee', status: 'pending' },
    ],
  },
  {
    id: 46,
    title: 'Beach Muscle Show',
    date: '2026-06-13',
    time: '12:00',
    type: 'public',
    category: 'none',
    iconId: 'beach',
    attendees: 25,
    confirmedAttendees: 18,
    location: 'Aron Beach',
    description: 'Flex it! Friendly fitness showcase by the sea. Spectators welcome.',
    hasVoting: true,
    hasTasks: false,
    hasPayment: false,
    organizerId: 'johnny',
    organizerName: 'Johnny Bravo',
    status: 'optimal',
    participants: [
      { id: 'me', name: 'Me', status: 'pending' },
      { id: '1', name: 'Samurai Jack', status: 'confirmed' },
      { id: '2', name: 'He-Man', status: 'confirmed' },
    ],
  },
  {
    id: 47,
    title: 'Spinach Cook-Off',
    date: '2026-06-27',
    time: '14:00',
    type: 'public',
    category: 'none',
    iconId: 'bbq',
    attendees: 18,
    confirmedAttendees: 14,
    location: 'Harbor Community Kitchen',
    description: 'Who makes the best spinach dish? Tasting and voting included!',
    hasVoting: true,
    hasTasks: true,
    hasPayment: false,
    organizerId: 'popeye',
    organizerName: 'Popeye',
    status: 'in-progress',
    tasks: [
      { id: 1, title: 'Buy spinach in bulk', completed: true, assignee: 'Popeye' },
      { id: 2, title: 'Prepare judging sheets', completed: false, assignee: 'Olive Oyl' },
    ],
    participants: [
      { id: 'me', name: 'Me', status: 'confirmed' },
      { id: '1', name: 'Olive Oyl', status: 'confirmed' },
      { id: '2', name: 'Bluto', status: 'confirmed' },
    ],
  },
  {
    id: 48,
    title: 'Forest Drum Circle',
    date: '2026-07-11',
    time: '17:00',
    type: 'public',
    category: 'none',
    iconId: 'music',
    attendees: 20,
    confirmedAttendees: 12,
    location: 'Woodland Clearing',
    description: 'Bring any percussion instrument. Beginners welcome!',
    hasVoting: false,
    hasTasks: false,
    hasPayment: false,
    organizerId: 'woody',
    organizerName: 'Woody Woodpecker',
    status: 'fixed',
    participants: [
      { id: 'me', name: 'Me', status: 'confirmed' },
      { id: '1', name: 'Buzz Buzzard', status: 'confirmed' },
    ],
  },
  {
    id: 49,
    title: 'Silent Film Night',
    date: '2026-07-25',
    time: '20:00',
    type: 'private',
    category: 'none',
    iconId: 'movie',
    attendees: 14,
    confirmedAttendees: 10,
    location: 'Retro Cinema',
    description: 'Classic silent films with live piano accompaniment.',
    hasVoting: false,
    hasTasks: false,
    hasPayment: true,
    paymentAmount: 15,
    currency: 'EUR',
    organizerId: 'pink',
    organizerName: 'Pink Panther',
    status: 'optimal',
    participants: [
      { id: 'me', name: 'Me', status: 'confirmed' },
      { id: '1', name: 'Inspector Clouseau', status: 'confirmed' },
    ],
  },
  {
    id: 50,
    title: 'Picnic Basket Contest',
    date: '2026-08-08',
    time: '11:00',
    type: 'public',
    category: 'none',
    iconId: 'picnic',
    attendees: 22,
    confirmedAttendees: 15,
    location: 'Jellystone Park',
    description: 'Who packs the best picnic basket? Prizes for creativity!',
    hasVoting: true,
    hasTasks: true,
    hasPayment: false,
    organizerId: 'yogi',
    organizerName: 'Yogi Bear',
    status: 'in-progress',
    tasks: [
      { id: 1, title: 'Set up picnic area', completed: true, assignee: 'Boo-Boo' },
      { id: 2, title: 'Organize judging', completed: false, assignee: 'Ranger Smith' },
    ],
    participants: [
      { id: 'me', name: 'Me', status: 'confirmed' },
      { id: '1', name: 'Boo-Boo Bear', status: 'confirmed' },
      { id: '2', name: 'Cindy Bear', status: 'pending' },
    ],
  },
  {
    id: 51,
    title: 'Lazy Sunday Brunch',
    date: '2026-08-30',
    time: '11:00',
    type: 'private',
    category: 'none',
    iconId: 'coffee',
    attendees: 8,
    confirmedAttendees: 6,
    location: 'Cat\'s Café',
    description: 'All-you-can-eat brunch. Naps encouraged afterward.',
    hasVoting: false,
    hasTasks: false,
    hasPayment: true,
    paymentAmount: 22,
    currency: 'EUR',
    organizerId: 'garfield',
    organizerName: 'Garfield',
    status: 'fixed',
    participants: [
      { id: 'me', name: 'Me', status: 'confirmed' },
      { id: '1', name: 'Odie', status: 'confirmed' },
      { id: '2', name: 'Nermal', status: 'pending' },
    ],
  },
  {
    id: 52,
    title: 'Honey Festival',
    date: '2026-09-12',
    time: '10:00',
    type: 'public',
    category: 'none',
    iconId: 'party',
    attendees: 30,
    confirmedAttendees: 20,
    location: 'Hundred Acre Wood',
    description: 'Honey tasting, bee workshops, and nature walks.',
    hasVoting: true,
    hasTasks: true,
    hasPayment: true,
    paymentAmount: 8,
    currency: 'EUR',
    organizerId: 'pooh',
    organizerName: 'Winnie the Pooh',
    status: 'optimal',
    tasks: [
      { id: 1, title: 'Collect honey samples', completed: true, assignee: 'Pooh' },
      { id: 2, title: 'Build information boards', completed: false, assignee: 'Rabbit' },
      { id: 3, title: 'Set up tasting station', completed: false, assignee: 'Piglet' },
    ],
    participants: [
      { id: 'me', name: 'Me', status: 'confirmed' },
      { id: '1', name: 'Piglet', status: 'confirmed' },
      { id: '2', name: 'Tigger', status: 'confirmed' },
      { id: '3', name: 'Eeyore', status: 'pending' },
    ],
  },
  {
    id: 53,
    title: 'Adventure Treasure Hunt',
    date: '2026-09-26',
    time: '09:00',
    type: 'public',
    category: 'none',
    iconId: 'trip',
    attendees: 16,
    confirmedAttendees: 12,
    location: 'Old Town Streets',
    description: 'Teams of 4 race to solve clues across the city. Great snacks!',
    hasVoting: false,
    hasTasks: true,
    hasPayment: true,
    paymentAmount: 10,
    currency: 'EUR',
    organizerId: 'tintin',
    organizerName: 'Tintin',
    status: 'in-progress',
    tasks: [
      { id: 1, title: 'Hide clues around town', completed: true, assignee: 'Tintin' },
      { id: 2, title: 'Prepare team kits', completed: false, assignee: 'Captain Haddock' },
    ],
    participants: [
      { id: 'me', name: 'Me', status: 'confirmed' },
      { id: '1', name: 'Captain Haddock', status: 'confirmed' },
      { id: '2', name: 'Professor Calculus', status: 'confirmed' },
      { id: '3', name: 'Thomson', status: 'pending' },
    ],
  },
  // === 25 new events: 10 by Andor (my events), 15 by cartoon characters ===
  { id: 54, title: 'Rooftop Barbecue', date: '2026-02-28', time: '18:00', type: 'private', category: 'friends', iconId: 'bbq', attendees: 12, confirmedAttendees: 9, location: 'Downtown Rooftop', description: 'Grilling and sunset views with the crew.', hasVoting: true, hasTasks: true, hasPayment: false, organizerId: 'me', organizerName: 'Andor', status: 'in-progress', participants: [{ id: '1', name: 'Homer Simpson', status: 'confirmed' }, { id: '2', name: 'Barney Gumble', status: 'pending' }] },
  { id: 55, title: 'Grandma\'s Recipe Day', date: '2026-03-05', time: '11:00', type: 'private', category: 'family', iconId: 'dinner', attendees: 8, confirmedAttendees: 8, location: 'Family Kitchen', description: 'Cooking traditional recipes together.', hasVoting: false, hasTasks: true, hasPayment: false, organizerId: 'me', organizerName: 'Andor', status: 'fixed', participants: [{ id: '1', name: 'Marge Simpson', status: 'confirmed' }, { id: '2', name: 'Lisa Simpson', status: 'confirmed' }] },
  { id: 56, title: 'Product Launch Workshop', date: '2026-03-12', time: '14:00', type: 'private', category: 'work', iconId: 'meeting', attendees: 20, confirmedAttendees: 15, location: 'Tech Hub', description: 'Internal workshop for the new product launch.', hasVoting: true, hasTasks: true, hasPayment: false, organizerId: 'me', organizerName: 'Andor', status: 'optimal', participants: [{ id: '1', name: 'Bugs Bunny', status: 'confirmed' }, { id: '2', name: 'Daffy Duck', status: 'pending' }] },
  { id: 57, title: 'Sunday Bike Ride', date: '2026-03-20', time: '08:00', type: 'public', category: 'sports', iconId: 'cycling', attendees: 10, confirmedAttendees: 7, location: 'River Trail', description: 'Leisurely 30km cycling tour along the river.', hasVoting: false, hasTasks: false, hasPayment: false, organizerId: 'me', organizerName: 'Andor', status: 'in-progress', participants: [{ id: '1', name: 'Lance Armstrong Jr.', status: 'confirmed' }, { id: '2', name: 'Mickey Mouse', status: 'confirmed' }] },
  { id: 58, title: 'Spring Break Getaway', date: '2026-04-02', time: '06:00', type: 'private', category: 'holiday', iconId: 'travel', attendees: 6, confirmedAttendees: 5, location: 'Coastal Resort', description: 'Three days of sun, sea, and relaxation.', hasVoting: true, hasTasks: true, hasPayment: true, paymentAmount: 220, currency: 'EUR', organizerId: 'me', organizerName: 'Andor', status: 'optimal', participants: [{ id: '1', name: 'Patrick Star', status: 'confirmed' }, { id: '2', name: 'SpongeBob SquarePants', status: 'confirmed' }] },
  { id: 59, title: 'Indie Film Screening', date: '2026-04-08', time: '19:00', type: 'public', category: 'none', iconId: 'movie', attendees: 25, confirmedAttendees: 18, location: 'Art House Cinema', description: 'Local indie films with Q&A session.', hasVoting: false, hasTasks: true, hasPayment: true, paymentAmount: 12, currency: 'EUR', organizerId: 'me', organizerName: 'Andor', status: 'in-progress', participants: [{ id: '1', name: 'Squidward Tentacles', status: 'confirmed' }, { id: '2', name: 'Lisa Simpson', status: 'pending' }] },
  { id: 60, title: 'Chess Night', date: '2026-04-15', time: '19:30', type: 'private', category: 'friends', iconId: 'gaming', attendees: 6, confirmedAttendees: 6, location: 'My Place', description: 'Blitz and rapid chess with snacks.', hasVoting: false, hasTasks: false, hasPayment: false, organizerId: 'me', organizerName: 'Andor', status: 'fixed', participants: [{ id: '1', name: 'Lisa Simpson', status: 'confirmed' }, { id: '2', name: 'Dexter', status: 'confirmed' }] },
  { id: 61, title: 'Easter Family Lunch', date: '2026-04-20', time: '13:00', type: 'private', category: 'family', iconId: 'easter', attendees: 14, confirmedAttendees: 12, location: 'Parents\' House', description: 'Easter lunch with egg hunt for the kids.', hasVoting: true, hasTasks: true, hasPayment: false, organizerId: 'me', organizerName: 'Andor', status: 'optimal', participants: [{ id: '1', name: 'Bart Simpson', status: 'confirmed' }, { id: '2', name: 'Maggie Simpson', status: 'confirmed' }] },
  { id: 62, title: 'Sprint Retrospective', date: '2026-04-25', time: '10:00', type: 'private', category: 'work', iconId: 'meeting', attendees: 12, confirmedAttendees: 12, location: 'Office Room B', description: 'Team sprint retro and planning for next cycle.', hasVoting: false, hasTasks: false, hasPayment: false, organizerId: 'me', organizerName: 'Andor', status: 'fixed', participants: [{ id: '1', name: 'Bugs Bunny', status: 'confirmed' }, { id: '2', name: 'Porky Pig', status: 'confirmed' }] },
  { id: 63, title: 'Rock Climbing Session', date: '2026-05-01', time: '17:00', type: 'public', category: 'sports', iconId: 'sports', attendees: 8, confirmedAttendees: 6, location: 'Urban Climb Gym', description: 'Beginner-friendly indoor climbing.', hasVoting: false, hasTasks: false, hasPayment: true, paymentAmount: 18, currency: 'EUR', organizerId: 'me', organizerName: 'Andor', status: 'in-progress', participants: [{ id: '1', name: 'Sandy Cheeks', status: 'confirmed' }, { id: '2', name: 'Shaggy Rogers', status: 'pending' }] },
  { id: 64, title: 'Disney Night at the Club', date: '2026-05-07', time: '21:00', type: 'public', category: 'friends', iconId: 'party', attendees: 50, confirmedAttendees: 35, location: 'Club Downtown', description: 'Theme night with Disney hits and costumes!', hasVoting: false, hasTasks: true, hasPayment: true, paymentAmount: 15, currency: 'EUR', organizerId: 'mickey', organizerName: 'Mickey Mouse', status: 'in-progress', participants: [{ id: 'me', name: 'Me', status: 'confirmed' }, { id: '1', name: 'Minnie Mouse', status: 'confirmed' }, { id: '2', name: 'Donald Duck', status: 'pending' }] },
  { id: 65, title: 'Simpson Family Cookout', date: '2026-05-14', time: '12:00', type: 'private', category: 'family', iconId: 'bbq', attendees: 12, confirmedAttendees: 10, location: 'Simpson Backyard', description: 'D\'oh-lightful BBQ with the whole family.', hasVoting: false, hasTasks: true, hasPayment: false, organizerId: 'homer', organizerName: 'Homer Simpson', status: 'optimal', participants: [{ id: 'me', name: 'Me', status: 'confirmed' }, { id: '1', name: 'Marge Simpson', status: 'confirmed' }, { id: '2', name: 'Abe Simpson', status: 'pending' }] },
  { id: 66, title: 'Animation Studio Tour', date: '2026-05-21', time: '09:00', type: 'private', category: 'work', iconId: 'workshop', attendees: 15, confirmedAttendees: 12, location: 'Warner Bros. Studios', description: 'Behind-the-scenes tour of animation pipeline.', hasVoting: false, hasTasks: false, hasPayment: false, organizerId: 'daffy', organizerName: 'Daffy Duck', status: 'fixed', participants: [{ id: 'me', name: 'Me', status: 'confirmed' }, { id: '1', name: 'Bugs Bunny', status: 'confirmed' }] },
  { id: 67, title: 'Underwater Volleyball', date: '2026-05-28', time: '10:00', type: 'public', category: 'sports', iconId: 'beach', attendees: 16, confirmedAttendees: 12, location: 'Bikini Bottom Arena', description: 'Volleyball under the sea! SpongeBob style.', hasVoting: true, hasTasks: true, hasPayment: true, paymentAmount: 5, currency: 'EUR', organizerId: 'sandy', organizerName: 'Sandy Cheeks', status: 'in-progress', participants: [{ id: 'me', name: 'Me', status: 'pending' }, { id: '1', name: 'SpongeBob SquarePants', status: 'confirmed' }, { id: '2', name: 'Patrick Star', status: 'confirmed' }] },
  { id: 68, title: 'Griffin Family Vacation', date: '2026-06-04', time: '07:00', type: 'private', category: 'holiday', iconId: 'travel', attendees: 8, confirmedAttendees: 6, location: 'Quahog Beach House', description: 'Week at the beach. Giggity!', hasVoting: true, hasTasks: true, hasPayment: true, paymentAmount: 180, currency: 'EUR', organizerId: 'peter', organizerName: 'Peter Griffin', status: 'optimal', participants: [{ id: 'me', name: 'Me', status: 'confirmed' }, { id: '1', name: 'Lois Griffin', status: 'confirmed' }, { id: '2', name: 'Stewie Griffin', status: 'pending' }] },
  { id: 69, title: 'Haunted House Investigation', date: '2026-06-11', time: '20:00', type: 'private', category: 'none', iconId: 'halloween', attendees: 6, confirmedAttendees: 5, location: 'Old Manor', description: 'Ruh-roh! Mystery solving with the gang.', hasVoting: false, hasTasks: true, hasPayment: true, paymentAmount: 20, currency: 'EUR', organizerId: 'scooby', organizerName: 'Scooby-Doo', status: 'in-progress', participants: [{ id: 'me', name: 'Me', status: 'confirmed' }, { id: '1', name: 'Shaggy Rogers', status: 'confirmed' }, { id: '2', name: 'Velma Dinkley', status: 'confirmed' }] },
  { id: 70, title: 'Jazz Concert at the Library', date: '2026-06-18', time: '18:00', type: 'public', category: 'friends', iconId: 'music', attendees: 40, confirmedAttendees: 28, location: 'City Library Hall', description: 'Live jazz trio performance. All ages welcome.', hasVoting: false, hasTasks: false, hasPayment: true, paymentAmount: 10, currency: 'EUR', organizerId: 'lisa', organizerName: 'Lisa Simpson', status: 'optimal', participants: [{ id: 'me', name: 'Me', status: 'confirmed' }, { id: '1', name: 'Bleeding Gums Murphy', status: 'confirmed' }] },
  { id: 71, title: 'Simpson Siblings Reunion', date: '2026-06-25', time: '14:00', type: 'private', category: 'family', iconId: 'family', attendees: 10, confirmedAttendees: 8, location: 'Springfield Park', description: 'Catch-up with the extended Simpson clan.', hasVoting: false, hasTasks: true, hasPayment: false, organizerId: 'marge', organizerName: 'Marge Simpson', status: 'fixed', participants: [{ id: 'me', name: 'Me', status: 'confirmed' }, { id: '1', name: 'Patty Bouvier', status: 'confirmed' }, { id: '2', name: 'Selma Bouvier', status: 'pending' }] },
  { id: 72, title: 'Stand-Up Comedy Workshop', date: '2026-07-02', time: '19:00', type: 'private', category: 'work', iconId: 'workshop', attendees: 12, confirmedAttendees: 9, location: 'Comedy Club Basement', description: 'Learn joke structure from the masters.', hasVoting: true, hasTasks: false, hasPayment: true, paymentAmount: 25, currency: 'EUR', organizerId: 'bugs', organizerName: 'Bugs Bunny', status: 'in-progress', participants: [{ id: 'me', name: 'Me', status: 'confirmed' }, { id: '1', name: 'Daffy Duck', status: 'confirmed' }] },
  { id: 73, title: 'Jellyfish Catching Contest', date: '2026-07-09', time: '09:00', type: 'public', category: 'sports', iconId: 'beach', attendees: 20, confirmedAttendees: 14, location: 'Jellyfish Fields', description: 'Catch and release. Nets provided!', hasVoting: false, hasTasks: true, hasPayment: false, organizerId: 'patrick', organizerName: 'Patrick Star', status: 'optimal', participants: [{ id: 'me', name: 'Me', status: 'pending' }, { id: '1', name: 'SpongeBob SquarePants', status: 'confirmed' }, { id: '2', name: 'Sandy Cheeks', status: 'confirmed' }] },
  { id: 74, title: 'Red Baron Flying Camp', date: '2026-07-16', time: '10:00', type: 'public', category: 'holiday', iconId: 'travel', attendees: 15, confirmedAttendees: 10, location: 'Pilot Training Grounds', description: 'Ace pilot training. Dogfights optional.', hasVoting: false, hasTasks: true, hasPayment: true, paymentAmount: 50, currency: 'EUR', organizerId: 'snoopy', organizerName: 'Snoopy', status: 'in-progress', participants: [{ id: 'me', name: 'Me', status: 'confirmed' }, { id: '1', name: 'Charlie Brown', status: 'confirmed' }] },
  { id: 75, title: 'Krusty Birthday Bash', date: '2026-07-23', time: '19:00', type: 'public', category: 'friends', iconId: 'birthday', attendees: 100, confirmedAttendees: 65, location: 'KrustyLand', description: 'Celebrating the Krust-meister! Pyrotechnics!', hasVoting: false, hasTasks: true, hasPayment: false, organizerId: 'krusty', organizerName: 'Krusty the Clown', status: 'optimal', participants: [{ id: 'me', name: 'Me', status: 'confirmed' }, { id: '1', name: 'Bart Simpson', status: 'confirmed' }] },
  { id: 76, title: 'Sea Creature Family Day', date: '2026-07-30', time: '11:00', type: 'public', category: 'family', iconId: 'picnic', attendees: 25, confirmedAttendees: 18, location: 'Goo Lagoon Beach', description: 'Underwater picnic and games for all ages.', hasVoting: true, hasTasks: true, hasPayment: false, organizerId: 'sponge', organizerName: 'SpongeBob SquarePants', status: 'in-progress', participants: [{ id: 'me', name: 'Me', status: 'confirmed' }, { id: '1', name: 'Patrick Star', status: 'confirmed' }, { id: '2', name: 'Sandy Cheeks', status: 'pending' }] },
  { id: 77, title: 'Duckburg Business Summit', date: '2026-08-06', time: '08:00', type: 'private', category: 'work', iconId: 'meeting', attendees: 50, confirmedAttendees: 42, location: 'Scrooge McDuck Tower', description: 'Annual business strategy and partnerships.', hasVoting: false, hasTasks: true, hasPayment: false, organizerId: 'donald', organizerName: 'Donald Duck', status: 'fixed', participants: [{ id: 'me', name: 'Me', status: 'confirmed' }, { id: '1', name: 'Scrooge McDuck', status: 'confirmed' }] },
  { id: 78, title: 'Great Pumpkin Run', date: '2026-08-13', time: '08:00', type: 'public', category: 'sports', iconId: 'running', attendees: 200, confirmedAttendees: 150, location: 'Peanuts Farm', description: '10K run. Linus promises the Great Pumpkin will appear!', hasVoting: false, hasTasks: true, hasPayment: true, paymentAmount: 20, currency: 'EUR', organizerId: 'charlie', organizerName: 'Charlie Brown', status: 'optimal', participants: [{ id: 'me', name: 'Me', status: 'confirmed' }, { id: '1', name: 'Snoopy', status: 'confirmed' }, { id: '2', name: 'Lucy van Pelt', status: 'pending' }] },
]
