// Icon mapping - maps icon IDs to Heroicon components (like RAZ template)

import {
  CalendarIcon,
  MapPinIcon,
  SparklesIcon,
  PaperAirplaneIcon,
  BriefcaseIcon,
  TrophyIcon,
  FireIcon,
  CakeIcon,
  HeartIcon,
  SunIcon,
  HomeIcon,
  FilmIcon,
  MusicalNoteIcon,
  PuzzlePieceIcon,
  GiftIcon,
  MoonIcon,
  BeakerIcon,
  ClipboardDocumentListIcon,
  BookOpenIcon,
  TruckIcon,
  ArrowTrendingUpIcon,
  AcademicCapIcon,
} from '@heroicons/react/24/outline'
import type { IconId } from './types'

export const ICON_MAP: Record<
  IconId,
  React.ComponentType<React.SVGProps<SVGSVGElement>>
> = {
  calendar: CalendarIcon,
  family: CalendarIcon,
  party: SparklesIcon,
  travel: PaperAirplaneIcon,
  work: BriefcaseIcon,
  sports: TrophyIcon,
  bbq: FireIcon,
  hiking: MapPinIcon,
  birthday: CakeIcon,
  wedding: HeartIcon,
  dinner: FireIcon,
  beach: SunIcon,
  camping: HomeIcon,
  movie: FilmIcon,
  music: MusicalNoteIcon,
  gaming: PuzzlePieceIcon,
  ski: TrophyIcon,
  christmas: GiftIcon,
  newyear: SparklesIcon,
  easter: TrophyIcon,
  halloween: MoonIcon,
  coffee: BeakerIcon,
  meeting: ClipboardDocumentListIcon,
  workshop: BookOpenIcon,
  trip: TruckIcon,
  running: FireIcon,
  cycling: ArrowTrendingUpIcon,
  yoga: HeartIcon,
  picnic: SunIcon,
  graduation: AcademicCapIcon,
  baby: HeartIcon,
}
